language: java

before_install:
  - chmod +x mvnw

cache:
  directories:
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "anant-pawar-github"
    token:
      secure: "*********"

script:
  - ./mvnw clean install
  - ./mvnw sonar:sonar -Dsonar.projectKey=anant-pawar_workforce-optimization-service -Dsonar.host.url=https://sonarcloud.io