language: java

before_install:
  - chmod +x mvnw

cache:
  directories:
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "anant-pawar-github"
    token:
      secure: $SONAR_TOKEN

services:
  - docker

script:
  - ./mvnw clean install
  - ./mvnw sonar:sonar -Dsonar.projectKey=anant-pawar_workforce-optimization-service -Dsonar.host.url=https://sonarcloud.io
  - ./mvnw dockerfile:build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push anantpawar/workforce-optimization-service